doctrine_migrations:
    migrations_paths:
        'Booking\Shared\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
