version: '3'

services:

  nginx:
    container_name: booking-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fpm

  postgres:
    container_name: booking-postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booking
    ports:
      - "5433:5432"
    volumes:
      - booking_db:/var/lib/postgresql/data

  fpm:
    container_name: booking
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "2222:22"
      - "9090:9000"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  booking_db:
